### PR TITLE
Add basic parsing error management

### LINKED ISSUE #5: Parsing error management
Currently the parser panicks if it can't parse an entry:
```
thread 'main' panicked at 'invalid hour: ParseIntError { kind: InvalidDigit }', src/libcore/result.rs:997:5
stack backtrace:
   0: std::sys::unix::backtrace::tracing::imp::unwind_backtrace
             at src/libstd/sys/unix/backtrace/tracing/gcc_s.rs:39
   1: std::sys_common::backtrace::_print
             at src/libstd/sys_common/backtrace.rs:71
   2: std::panicking::default_hook::{{closure}}
             at src/libstd/sys_common/backtrace.rs:59
             at src/libstd/panicking.rs:197
   3: std::panicking::default_hook
             at src/libstd/panicking.rs:211
   4: std::panicking::rust_panic_with_hook
             at src/libstd/panicking.rs:474
   5: std::panicking::continue_panic_fmt
             at src/libstd/panicking.rs:381
   6: rust_begin_unwind
             at src/libstd/panicking.rs:308
   7: core::panicking::panic_fmt
             at src/libcore/panicking.rs:85
   8: core::result::unwrap_failed
   9: gst_log_parser::Entry::new
  10: <gst_log_parser::ParserIterator<R> as core::iter::traits::iterator::Iterator>::next
  11: gst_log_diff::main
  12: std::rt::lang_start::{{closure}}
  13: std::panicking::try::do_call
             at src/libstd/rt.rs:49
             at src/libstd/panicking.rs:293
  14: __rust_maybe_catch_panic
             at src/libpanic_unwind/lib.rs:87
  15: std::rt::lang_start_internal
             at src/libstd/panicking.rs:272
             at src/libstd/panic.rs:388
             at src/libstd/rt.rs:48
  16: main
  17: __libc_start_main
  18: _start
```

Maybe `Entry::new()` should return a `Result<Entry,...>` and gracefully handle failures?

### PR DESCRIPTION
**Pull request by philn**
Entry::new() now returns a Result<Entry, ParsingError> and no longer crashes
when it is unable to successfully parse a log line.

Fixes #5

I think this commit should be shipped in a 0.2.x release because it's an API break.

### CODE REVIEW

**Comment by gdesmott** [comment]
Looks great, thank you very much!

Are you sure regarding the API break? It doesn't affect the public API right? The `parse()` iteration is unchanged.

**Comment by philn** [comment]
`Entry` is a public struct though, so I think that implies its `impl` is public as well.

**Comment by gdesmott** [comment]
I don't think so. See for example `message_to_struct()` which is public while `new()` is not.

**Comment by philn** [comment]
Ah yeah right I was confused because of a refactoring started in another project where trait impl methods are public by default, but here you don't have traits, so everything's fine, no API break!

**Comment by gdesmott** [comment]
All good then! Thanks a lot of the patch; I'll push a release with it.

**Pull request merged**
