### PR TITLE
Flag examples as such in the build manifest & upgrade deps

### PR DESCRIPTION
**Pull request by philn**

### CODE REVIEW

**Comment by philn** [comment]
CI is unhappy:
```
--- stderr
`"pkg-config" "--libs" "--cflags" "glib-2.0 >= 2.42"` did not exit successfully: exit code: 1
--- stderr
Requested 'glib-2.0 >= 2.42' but version of GLib is 2.40.2
```

I'm trying now without the deps upgrade :)

**Review by gdesmott — COMMENTED** [review]
What's the actual benefit of using example rather than bin then?

**Comment by philn** [comment]
https://doc.rust-lang.org/stable/rust-by-example/testing/dev_dependencies.html

**Comment by philn** [comment]
dev-deps won't be propagated to crates depending on the lib, AFAIU :)

**Comment by gdesmott** [comment]
Perfect then. Merging this, feel free to open another ticket for the deps update.

**Pull request merged**
